# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - containers(printmangmnet)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://db92c468e5bc472592f52e70fa9b4774.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b29fc0f96ed64522aa81d4b448f69fbf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_338a9f8d1f3b409abd84263b1a7419af }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: db92c468e5bc472592f52e70fa9b4774.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b29fc0f96ed64522aa81d4b448f69fbf }}/db92c468e5bc472592f52e70fa9b4774/db92c468e5bc472592f52e70fa9b4774/azureml/azureml_ae9b088a130efdab38ad8f2224c5626f:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'printmangmnet'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'containers'
        slot-name: 'printmangmnet'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_88dadc0e217142e29814a3d710c27c01 }}
        images: 'db92c468e5bc472592f52e70fa9b4774.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b29fc0f96ed64522aa81d4b448f69fbf }}/db92c468e5bc472592f52e70fa9b4774/db92c468e5bc472592f52e70fa9b4774/azureml/azureml_ae9b088a130efdab38ad8f2224c5626f:${{ github.sha }}'